name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: master # 指定要检出的分支
      - name: Setup git user
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Add upstream
        run: git remote add upstream https://github.com/qwerttvv/Beijing-IPTV.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream changes
        run: git merge upstream/master --allow-unrelated-histories || true
      - name: Check for changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes::true"
          fi
      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: git push origin master
